# Generated by Django 4.1.9 on 2023-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10, null=True)),
                ('TrafficLightState', models.CharField(default=None, max_length=10, null=True)),
                ('timer', models.IntegerField(default=None, null=True)),
                ('interface', models.CharField(default=None, max_length=20, null=True)),
                ('camera', models.CharField(default=None, max_length=10, null=True)),
                ('isConfigure', models.BooleanField(default=False)),
                ('nbOfCars', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
