# Generated by Django 4.1.9 on 2023-10-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_env_zone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='env',
            old_name='zone_name',
            new_name='zoneName',
        ),
    ]
