# Generated by Django 4.1.9 on 2023-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0003_rename_zone_name_env_zonename'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='zoneDetectionCoord',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
