# Generated by Django 4.1.9 on 2023-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0004_env_zonedetectioncoord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='camera',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
