# Generated by Django 4.1.9 on 2023-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0005_alter_env_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='idCamera',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
