# Generated by Django 4.1.9 on 2023-10-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0006_env_idcamera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='idCamera',
        ),
    ]
