# Generated by Django 4.1.9 on 2023-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0007_remove_env_idcamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='videoCamera',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
